---
- name: geth - check geth is installed
  stat:
    path: "{{ geth_binary_path }}"
  register: geth_binary


- name: geth - download and extract binary
  unarchive:
    src: "{{ geth_binary_download_url }}"
    dest: "{{ geth_dir_binary }}"
    owner: "{{ geth_user }}"
    group: "{{ geth_group }}"
    remote_src: true
    mode: "0755"
    extra_opts: ['--strip-components=1']
  when: (not geth_binary.stat.exists) or (geth_reinstall)

- name: geth - write systemd unit
  template:
    src: service.j2
    dest: "{{ geth_dir_systemd }}/{{ geth_systemd_service_name }}.service"
    owner: "{{ geth_user }}"
    group: "{{ geth_group }}"
    mode: "0644"
  notify:
    - geth - restart

- name: geth - ensure service started
  systemd:
    name: "{{ geth_systemd_service_name }}"
    state: started
    daemon_reload: true
    enabled: true
