---
- import_tasks: prepare.yml
  tags:
    - geth-prepare
    - geth-config
    - geth-install

- import_tasks: configure.yml
  tags:
    - geth-config

- import_tasks: install.yml
  tags:
    - geth-install
